issue_42: ordering from most specific to least specific for team sett…
sensu-plugins/sensu-plugins-pagerduty pull request #43
Opened 2017-04-05 01:12 UTC by guru-beach

It seems to make more sense to have notifications go from most to least specific settings.   We have many cases where application level checks have different pager_teams and the teams creating those checks don't have access to the node level configurations for pd_override settings.   If no check team is configured, the node level config should be used, and if no node level config, the default api_key should be used.   

## Pull Request Checklist

**Is this in reference to an existing issue?**

#### General

- [ ] Update Changelog following the conventions laid out on [Keep A Changelog](http://keepachangelog.com/)

- [ ] Update README with any necessary configuration snippets

- [ ] Binstubs are created if needed

- [ ] RuboCop passes

- [ ] Existing tests pass 

#### New Plugins

- [ ] Tests

- [ ] Add the plugin to the README

- [ ] Does it have a complete header as outlined [here](http://sensu-plugins.io/docs/developer_guidelines.html#coding-style)

#### Purpose

#### Known Compatablity Issues

2017-04-30 18:25 UTC, majormoses requested changes
I still want other peoples feedback on this as I always use only check pagerduty team and do not rely on node/client level config for this. It looks fine to me other than needing to improve the changelog message to make this breaking change more obvious on this impact.

2017-04-30 18:25 UTC, majormoses commented on CHANGELOG.md
> +- Update check pager_team to override client pager_team setting
This needs to be called out as a breaking change. Also this is not really clear as to its intention. I would do something like this:
```
### Breaking Change
- changed the precedence of pager_team evaluation from `client -> check -> json_config`  to `check -> client -> json_config`  
```

This makes it much clearer for someone evaluating CHANGELOG to see the breaking change and its impact.

2017-04-30 18:26 UTC, majormoses commented
@guru-beach also can you please rebase? I see conflicts with master.

2017-05-02 16:23 UTC, majormoses commented
@guru-beach can you rebase and improve the CHANGELOG message? if so I think I am good with merging it after confirming with a few users on potential impact and use cases that I don't have/use.

2017-05-05 22:00 UTC, guru-beach commented on CHANGELOG.md
> +- Update check pager_team to override client pager_team setting
Thanks for the guidance.  This is one of my first merge requests ever :)   This is helpful.

2017-05-05 22:05 UTC, guru-beach commented
Hrm, I didn't update the test order, let me check into that.

2017-05-05 22:14 UTC, majormoses commented
also it looks like you still need to rebase to fix conflicts.

2017-05-06 19:58 UTC, majormoses commented
@guru-beach I still see conflicts do you need help rebasing? If you are ok with it I should be able to rebase your branch for you in your fork (assuming you allowed maintainers that when you opened the PR)

2017-05-25 18:07 UTC, guru-beach commented
@majormoses I may need help with the rebase.  Sorry.   This is the first time I've tried to do this in github and between projects.  I thought I did it properly, but apparently not.

2017-05-25 18:55 UTC, majormoses commented
Cool if you have issues after trying I can fix it for you, that being said here are the basic instructions:
1. setup sensu repo as a remote `git remote add upstream https://github.com/sensu-plugins/sensu-plugins-pagerduty.git`
1. fetch changes: `git fetch upstream`
1. git rebase upstream/master
1. At this point you may include conflicts that require manual changes with your editor to choose whether you want your changes or upstreams changes. After you have fixed these in each file that has a conflict `git status` should allow you to check if there are any remaining. You can then do a `git add $FILE_THAT_REQUIRED_CONFLICT_RESOLUTION` and `git rebase --continue` to move to the next commit.
1. Once everything looks good locally you can then do a `git push -f` to force push as your changes locally vs the remote (on the git server) are different and need to be told don't try to resolve conflicts accept my new source of truth.

2017-05-25 19:02 UTC, majormoses commented
I really need to write this up somewhere as it is a big obstacle to get people to contribute even outside the context of a public github project I have to somewhat regularly teach people to rebase.

2017-05-26 23:59 UTC, majormoses commented
@guru-beach any progress on this or should I fix this up?

2017-06-01 16:29 UTC, majormoses commented
@guru-beach I got around to rebasing this for you.

2017-06-01 16:30 UTC, majormoses approved these changes

2017-06-01 16:31 UTC, merged

2017-06-01 16:37 UTC, majormoses commented
released: https://rubygems.org/gems/sensu-plugins-pagerduty/versions/3.0.0

2017-06-01 18:16 UTC, guru-beach commented
Sorry about that Ben, I've been on a road trip and wasn't staying up with my email.   I've reviewed the changes and will keep the instructions for further use.   

Thanks for the help!